version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AUTHOR=Ibragim
      - UUID=${HOSTNAME:-default-uuid}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/hostname"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge

